version: '3.1'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"