version: '3.1'

services:
#  telegram-bot:
#    build:
#      context: .
#    ports:
#    - "80:3000"
#    environment:
#    - CONSUL_HTTP_ADDR=consul:8500
#    - REGION=us-east-1
#    - SERVICE_NAME=dev-ws-pdf-services-main
#    - SERVICE_ENV=dev
#    - PORT=3000
#    depends_on:
#      - consul
#      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
